#+ endpoint: http://localhost:1234/sparql/

prefix obo: <http://purl.obolibrary.org/obo/>
prefix faldo: <http://biohackathon.org/resource/faldo#>
prefix TAIR10: <http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/>


SELECT DISTINCT (str(?regulator) AS ?candidate_gene)
WHERE{

# determine the QTL interval
VALUES ?ref{ TAIR10:5 }
FILTER (?begin_pos >= 2000000 && ?end_pos <= 4000000) .

# get the list of candidate in the QTL interval
?gene a                     obo:SO_0001217 .
?gene faldo:location            ?gene_loc .
?gene_loc faldo:begin           ?begin ;
          faldo:end             ?end ;
          faldo:reference       ?ref .
          ?begin faldo:position ?begin_pos .
          ?end faldo:position   ?end_pos .

# get the gene label
?gene rdfs:label ?regulator .

}
