#+ summary: Get genes given an interval.
#+ tags:
#+  - Get genes given an interval.
#+ enumerate:
#+  - chro:
#+    - http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/1
#+    - http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/2
#+    - http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/3
#+    - http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/4
#+    - http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/5

prefix obo: <http://purl.obolibrary.org/obo/>
prefix faldo: <http://biohackathon.org/resource/faldo#>
prefix TAIR10: <http://rdf.ebi.ac.uk/resource/ensembl/33/arabidopsis_thaliana/TAIR10/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?candidate_gene
WHERE
{
SELECT
DISTINCT (str(?regulator) AS ?candidate_gene)
?begin_pos
?end_pos
WHERE
{
{
# get the list of candidate in the QTL interval
?gene a                     obo:SO_0001217 .

# query the candidate that shared bp go term
?gene faldo:location            ?gene_loc .
?gene_loc faldo:begin           ?begin ;
          faldo:end             ?end ;
          faldo:reference       ?_chro_iri .
?begin    faldo:position        ?begin_pos .
?end      faldo:position        ?end_pos .


# get the gene label
?gene rdfs:label ?regulator .
}
FILTER( ?begin_pos >= ?_begin_xsd_integer &&
          ?end_pos <= ?_end_xsd_integer )

}
}
