#+ summary: Get genes that overlap with a QTL identified by ID.
#+ tags:
#+  - Get genes in a QTL
#+ defaults:
#+  - qtlid: QTL:3859326_3_2

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX Gene: <http://purl.obolibrary.org/obo/SO_0001217>
PREFIX QTL: <http://purl.obolibrary.org/obo/SO_0000771>

SELECT
  ?gene_id
FROM <http://solgenomics.net/genome/Solanum_lycopersicum>
FROM <http://solgenomics.net/genome/Solanum_tuberosum>
FROM <http://europepmc.org>
WHERE {
  ?gene a Gene: ;
    dcterms:identifier ?gene_id .
  ?qtl a QTL: ;
    dcterms:identifier ?_qtlid ;
    so:overlaps ?gene .
}
